apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-djue
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-agjo-tenant/rhtap-demo-app/hacbs-test-project-djue@sha256:e975dfd23ff04fb44d63bfcabed8caebcd58e2655844ef5cba3fac3d5795a844
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
