apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-djue
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-djue
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-djue
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-djue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-djue
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-agjo-tenant/rhtap-demo-app/hacbs-test-project-djue@sha256:d997fb6cd7222911a4be36c0e0a319f9cae40c709e696a1ed465b4831d7399a7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
